create table if not exists stock_master (
  code text not null,
  exchange text not null,
  name text,
  industry_code text,
  industry_name text,
  industry_short_name text,
  industry_classification text,
  update_date date,
  trade_date date,
  universe text,
  is_active boolean,
  first_seen_date date,
  last_seen_date date,
  inactive_date date,
  float_shares numeric,
  float_shares_yi numeric,
  share_snapshot_date date,
  "industry_name_SINA" text,
  earnings_per_share numeric,
  earnings_per_share_updated_at timestamptz,
  imported_at timestamptz not null default now(),
  primary key (code, exchange)
);

alter table stock_master
  drop column if exists industry,
  add column if not exists industry_code text,
  add column if not exists industry_name text,
  add column if not exists industry_short_name text,
  add column if not exists float_shares numeric,
  add column if not exists float_shares_yi numeric,
  add column if not exists share_snapshot_date date,
  add column if not exists "industry_name_SINA" text,
  add column if not exists earnings_per_share numeric,
  add column if not exists earnings_per_share_updated_at timestamptz;

create table if not exists stock_keywords (
  id integer generated by default as identity primary key,
  key_code text not null default 'sina',
  key_name text not null,
  fav_flg boolean not null default false,
  display_num integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (key_name)
);

create index if not exists stock_keywords_fav_display_idx
  on stock_keywords (fav_flg desc, display_num asc, key_name asc);

create table if not exists stock_key_map (
  code text not null,
  exchange text not null,
  key_code text not null default 'sina',
  key_name text not null,
  place_num integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (code, exchange, key_name)
);

create index if not exists stock_key_map_key_name_idx
  on stock_key_map (key_name);

create table if not exists stock_favorite_stocks (
  code text not null,
  exchange text not null,
  display_num integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (code, exchange)
);

alter table stock_favorite_stocks
  add column if not exists display_num integer;

create index if not exists stock_favorite_stocks_updated_idx
  on stock_favorite_stocks (updated_at desc);

create index if not exists stock_favorite_stocks_display_idx
  on stock_favorite_stocks (display_num asc, code asc, exchange asc);

create table if not exists stock_shareholder_research (
  report_date date not null,
  code text not null,
  exchange text not null,
  secucode text not null,
  holder_total_num numeric,
  total_num_ratio numeric,
  avg_free_shares numeric,
  avg_freeshares_ratio numeric,
  hold_focus text,
  source text not null default 'eastmoney_f10_holdernum',
  imported_at timestamptz not null default now(),
  primary key (report_date, code, exchange)
);

create index if not exists stock_shareholder_research_code_date_idx
  on stock_shareholder_research (code, exchange, report_date desc);
